# Generated by Django 5.0.1 on 2024-02-05 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productocategoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 1, 6, 15, 630085, tzinfo=datetime.timezone.utc), editable=False, null=True, verbose_name='fecha de actualización'),
        ),
    ]
