# Generated by Django 5.0.1 on 2024-02-05 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 1, 7, 34, 129177, tzinfo=datetime.timezone.utc), editable=False, null=True, verbose_name='fecha de actualización'),
        ),
    ]
